"""empty message

Revision ID: 16edffa481cf
Revises: 4a5217d669c0
Create Date: 2024-05-28 18:54:05.863465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16edffa481cf'
down_revision = '4a5217d669c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_on', sa.DateTime(), nullable=True),
    sa.Column('feedback_employerid', sa.Integer(), nullable=True),
    sa.Column('feedback_jobseekerid', sa.Integer(), nullable=True),
    sa.Column('feedback_applicationid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_applicationid'], ['application.application_id'], ),
    sa.ForeignKeyConstraint(['feedback_employerid'], ['employers.employer_id'], ),
    sa.ForeignKeyConstraint(['feedback_jobseekerid'], ['jobseekers.jobseeker_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('message_employerid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_jobseekerid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_applicationid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sent_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_applicationid'], ['application.application_id'], name='message_ibfk_3'),
    sa.ForeignKeyConstraint(['message_employerid'], ['employers.employer_id'], name='message_ibfk_1'),
    sa.ForeignKeyConstraint(['message_jobseekerid'], ['jobseekers.jobseeker_id'], name='message_ibfk_2'),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('feedback')
    # ### end Alembic commands ###
