"""empty message

Revision ID: 4a5217d669c0
Revises: 21e2bec55eab
Create Date: 2024-05-28 12:24:14.183281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a5217d669c0'
down_revision = '21e2bec55eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_lgaid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employer_typeid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'type', ['employer_typeid'], ['type_id'])
        batch_op.create_foreign_key(None, 'lga', ['employer_lgaid'], ['lga_id'])
        batch_op.drop_column('employer_company_sub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_company_sub', mysql.ENUM('Free', 'Starter', 'Pro', 'Elite'), server_default=sa.text("'Free'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employer_typeid')
        batch_op.drop_column('employer_lgaid')

    op.drop_table('type')
    # ### end Alembic commands ###
