"""empty message

Revision ID: a53091453b0c
Revises: ca3ade28f464
Create Date: 2024-05-26 05:53:10.232262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a53091453b0c'
down_revision = 'ca3ade28f464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.drop_constraint('employers_ibfk_2', type_='foreignkey')
        batch_op.drop_column('employer_lgaid')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('job_lgaid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lga', ['job_lgaid'], ['lga_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_lgaid')
        batch_op.drop_column('language')

    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_lgaid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('employers_ibfk_2', 'lga', ['employer_lgaid'], ['lga_id'])

    # ### end Alembic commands ###
