"""empty message

Revision ID: cc717576c935
Revises: a53091453b0c
Create Date: 2024-05-26 22:32:22.718429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc717576c935'
down_revision = 'a53091453b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_firstname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('admin_lastname', sa.String(length=100), nullable=False))
        batch_op.drop_column('admin_fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_fullname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('admin_lastname')
        batch_op.drop_column('admin_firstname')

    # ### end Alembic commands ###
